<?php

/**
 * @file
 * Primary module hooks for fresh_apples_show_page module.
 */

function fresh_apples_show_page_theme() {
  return [
    'region__content__show' => [
      'template' => 'region--content--show',
      'base hook' => 'region',
    ],
  ];
}

function fresh_apples_show_page_theme_suggestions_region_alter(array &$suggestions, array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node) {
    return;
  }

  $content_type = $node->bundle();

  if ($content_type === 'show') {
    if ($variables['theme_hook_original'] && $variables['theme_hook_original'] === 'region') {
      $suggestions[] = 'region__content__show';
    }
  }
}
