<?php

/**
 * @file
 * Primary module hooks for fresh_apples_show_page module.
 */

function fresh_apples_show_page_theme() {
  return [
    'region__content__show' => [
      'template' => 'region--content--show',
      'base hook' => 'region',
    ],
    'node__show' => [
      'template' => 'node--show',
      'base hook' => 'node',
    ],
  ];
}

function fresh_apples_show_page_theme_suggestions_region_alter(array &$suggestions, array &$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node) {
    return;
  }

  $content_type = $node->bundle();

  if ($content_type === 'show') {
    if ($variables['theme_hook_original'] && $variables['theme_hook_original'] === 'region') {
      $suggestions[] = 'region__content__show';
    }
  }
}

function fresh_apples_show_page_preprocess_page(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node) {
    return;
  }

  $content_type = $node->bundle();

  if ($content_type === 'show') {
    $variables['#attached']['library'][] = 'fresh_apples_show_page/tailwind';
    $variables['#attached']['library'][] = 'fresh_apples_show_page/swiper';
    $variables['#attached']['library'][] = 'fresh_apples_show_page/fresh_apples_show_page';
  }
}

function fresh_apples_show_page_preprocess_node(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node) {
    return;
  }

  $content_type = $node->bundle();
  $user_roles = \Drupal::currentUser()->getRoles();

  if (in_array('reviewer', $user_roles)) {
    $variables['user_role'] = 'reviewer';
  }
  else if (in_array('authenticated', $user_roles)) {
    $variables['user_role'] = 'regular';
  }
  else {
    $variables['user_role'] = 'unauthenticated';
  }

  if ($content_type === 'show') {
    $variables['show_data'] = \Drupal::service('fresh_apples_show_page.service')->prepareShowData($node);
  }
}
